# L4A: Lists and Tuples

### Lists

These represent a linear series of items / values. The values in a list are _ordered_ and can be accessed via an _index_. Lists are iterable and thus are prime use-cases for _for-loops_. They can contain objects of any type, including lists themselves (which means _nested lists_ are a thing).

These have various uses such as storing a list of classes for a class scheduler, a list of transactions for a e-wallet application, a list of items in a shopping cart, and more. 

Let's look at a few examples of lists:

In [0]:
# A list of numbers from 0-10
nums_1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# You can get the same list using the range() function and casting it
nums_2 = list(range(0, 11))

print(nums_1, nums_2)

In [0]:
# A list containing strings
words_list = ["foo", "bar", "baz", "qux", "quux", "corge"]

for word in words_list:
  print(word)

In [0]:
diff_vals = [1, 2, 3, 4.5, '6', '789', 'Howdy!']

for val in diff_vals:
  print(diff_vals)

Strings can be thought of as lists of single characters. We also have access to a `split(<split_character>)` function that allows us to convert a string into a list of string split on the given character.

**Note:** This does _not_ mean that all list functions work on Strings, they're still a separate data type. Thinking of them as lists of characters just helps with intuition.

In [0]:
# Examples of strings & the split function

items = "Apples, Oranges, Pears, Mangoes"

# We can convert the `items` string into a list by splitting it on the ", " string
item_list = items.split(", ")
item_list

In [0]:
# Converting a string into a list of its characters
word = "Howdy!"

# The string can directly be typecasted to a list
word_chars = list(word)
word_chars

#### Indexing

To access a specific item in a list, you can use its _index_. An index is just the position at which an item exists in a list. The only thing to note is that the _first_ item in a list is at index _0_. 

Thus for a list that has 10 items in it, the item indices range between 0-9.

Also, you can get the length of a list using the `len(<list_variable/value>)` function.

In [0]:
# Here's a few examples of how indexing works using a shopping cart:

shopping_cart_items = ["Apple", "Oranges", "Flour", "Sugar", "Salt", "Pepper"]

# 'Apple' is the first item, and will be at index 0
print("The FIRST item in the list is", shopping_car_items[0])

# 'Flour' is the third item and is at index 2
print("The THIRD item in the list is", shopping_cart_items[2])

# The length of the list is 6, thus 'Pepper', the last item, should be at index 5
print("The LAST item in the list is", shopping_cart_items[5])

# You can access the last element using the `len` function too
print("The LAST item in the list is", shopping_cart_items[len(shopping_cart_items)-1])

# Python also allows negative indices (other languages might not allow them).
# These represent positions from the END of the list
print("The LAST item in the list is", shopping_cart_items[-1])

In [0]:
# We can print out the items in a list using their indices

shopping_cart_items = ["Apple", "Oranges", "Flour", "Sugar", "Salt", "Pepper"]

for i in range(len(shopping_cart_items)):
  print(shopping_cart_items[i])

In [0]:
# Trying to access an out-of-bounds index (greater than length of the list) will fail

shopping_cart_items = ["Apple", "Oranges", "Flour", "Sugar", "Salt", "Pepper"]
shopping_cart_items[20] = "Shoes"

#### List Slices

It's often useful to access '_slices_' or subsections of a list, instead of the whole list. We might want to access the last _n_ things added to a shopping list, or check the first few transactions made using our card. _Slices_ are a good solution for such cases, allowing easy accesses to subsections of a list.

The syntax for slices is similar to indexing, but we specify a start index or an end index or both. We can also supply a step size if needed:

```
<list>[<start_index>=0 : <end_index>=len(<list>) : <step_size>=1]
```

Step size can be negative if we want to step backwards.

In [0]:
# Let's use slices on the first 20 natural numbers
nums = list(range(1, 21))
print(nums)

In [0]:
# Getting the first 5 natural numbers (1-5) using slices
first_five = nums[:5]
print("First five numbers from the list:", first_five)

In [0]:
# Getting the last 5 natural numbers in the list (16-20)
last_five = nums[15:] # 15 is the index of the number 16 in the list
print("Last five numbers from the list:", last_five)

In [0]:
# Getting the numbers 10-15 from the list
middle_five = nums[9:15]
print("Middle five numbers of the list:", middle_five)

In [0]:
# Getting all the odd numbers from the list
odds = nums[::2] # Get the whole list with step size 2
print("Odds numbers in the list:", odds)

In [0]:
nums = list(range(1, 21))
#reversing the order
reverse = nums[::-1]
print(reverse)

In [0]:
# Get all the even numbers between 10-18
evens = nums[9:18:2]
print("Even numbers between 10-18:", evens)

### Nested Lists

As items inside a list can be of any type, they can be a list too, which allows us to have nested lists in Python. A common use of nested lists is to represent **matrices**. 

If you access an index of a nested list, the value returned will be a list as well, which can then be further indexed to access values.

In [0]:
# Let's use nested lists to create a matrix that looks like this:
# 1 2 3
# 4 5 6
# 7 8 8
# For people with previous coding experience, nested lists can be thought of as
# higher-dimensional arrays

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# We can access the first row using normal indexing
print(matrix[0])

# We can access elements within a row using chained-indexing
print(matrix[1][0])
print(matrix[1][1])
print(matrix[1][2])

### List Functions:

All of the function below _mutate_ the list _in place_, which means the list object they're called on is changed. 

* `<list>.append(<item>)`: The **Append** function adds the given item to the end of the list.
* `<list>.remove(<item>)`: The **Remove** function finds the _first occurence_ of the given item in the list and removes it.
* `<list>.pop(<index>`: The **Pop** function removes and returns the element at the provided index from the given list
* `<list>.insert(<index>, <item>)`: The **Insert** function inserts the given item at the given index in the list. It will push up all elements after that index by one.
* `<list>.count(<element>)`: The **Count** function returns the number of occurences of the given element within the list
* `<list>.sort()`: The **Sort** function sorts the given list in _ascending_ order. The list needs to contain comparable values for the function to work
* `<list>.clear()`: The **Clear** function removes all the elements from a given list
* `<list>.reverse()`: This function reverses the given list.

In [0]:
# Let's see how appending works

list_items = [1, 2, 3, 4, 5]
print("Original list:", list_items)

list_items.append(6)
print(list_items)

# We can append another data type
list_items.append('7')
print(list_items)

# We can append a list too, which will make our object a nested list
list_items.append([8, 9, 10])
print(list_items)

In [0]:
# An example of how removing works

# Note: "Flour" appears twice
shopping_list = ["Apple", "Oranges", "Flour", "Sugar", "Salt", "Pepper", "Flour"]

shopping_list.remove("Oranges")
print(shopping_list)

# Removing "Flour", which has two instances in the list, will only remove the first
# one.
shopping_list.remove("Flour")
print(shopping_list)

In [0]:
# Trying to remove something that doesn't exist in the list will fail
shopping_list = ["Apple", "Oranges", "Flour", "Sugar", "Salt", "Pepper", "Flour"]
shopping_list.remove("Shoes")

In [0]:
# An example of how popping works
# We'll use the sample example as above, but have to use indices this time around

shopping_list = ["Apple", "Oranges", "Flour", "Sugar", "Salt", "Pepper", "Flour"]

# Pop "Oranges" using its index
shopping_list.pop(1)
print(shopping_list)

# We can pop the last "Flour" by using negative indexing
shopping_list.pop(-1)
print(shopping_list)

In [0]:
# Trying to pop an invalid index will fail
shopping_list = ["Apple", "Oranges", "Flour", "Sugar", "Salt", "Pepper", "Flour"]
shopping_list.pop(20)

In [0]:
# An example of how inserting works

# We're missing 2 & 6
nums = [1, 3, 4, 5]

# New list should be [1, 2, 3, 4, 5]
nums.insert(1, 2)
print(nums)

# Inserting into the length index resembles using `append()`
nums.insert(len(nums), 6)
print(nums)

In [0]:
# Insertion works with out-of-range indices as well
nums = [1, 3, 4, 5]

# An out-of-range positive index will add the value to the end of the list
nums.insert(20, 10)
print(nums)

# An out-of-range negative index will add the value to the beginning of the list
nums.insert(-20, -10)
print(nums)

In [0]:
# Examples of count
names = ["George", "John", "Mark", "David", "Mark"]

mark_count = names.count("Mark")
print(f"Mark appears in the list {num_mark} times")

# If the given element doesn't exist in the list, it returns 0
karen_count = names.count("Karen")\
print(f"Karen appears in the list {karen_count} times")

In [0]:
# Examples of sort
nums = [2, 3, 1, 7, 5, 6]
print("Unsorted list:", nums)

nums.sort()
print("Sorted list:", nums)

In [0]:
# If the elements in the list are not comparable, the `sort` throws an error
items_list = [5, 4, 3, "Howdy", 1.2]

# This will fail
items_list.sort()

In [0]:
# Example of clear
nums = [1, 2, 3, 4, 5]
print(nums)

nums.clear()
print("Nums after clearing:", nums)

In [0]:
# An examples of how reversing works
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9]

nums.reverse()
print("Reversed list:", nums)

# We can get the original list by reversing it again
nums.reverse()
print("We have the original list back:", nums)

# We can get a reversed list using slicing too!
print("Reversed list using slicing:", nums[::-1])
# Note: slicing does not change the list in place, it returns a new list

In [0]:
# Slicing-based reversing works for strings too!
word = "Howdy!"
word[::-1]

### List Operators

* `+`: The sum operator represents _concatenation_ for lists. It will join the two lists provided to it and return a single list

  The usage and operation is the same for Strings!

* `*`: The multiply operator represents _repetition_. Any list can be multiplied by a number `n` and the elements will be repeated `n` times in the returned list

  The usage and operation of `*` is same for Strings too.

In [0]:
# Examples of concatenation

names_1 = ["George", "John"]
names_2 = ["David", "Mark"]

# This will create a single list with all 4 names
names = names_1 + names_2
print("Concatenated names:", names)

# Nested lists are treated as single objects
nums_1 = [[1, 2, 3]]
nums_2 = [[4, 5, 6]]

# The single list will contain two elements, each of which are lists
nums = nums_1 + nums_2
nums

In [0]:
# Concatenation works in similar ways for strings
word_1 = "Howdy"
word_2 = "y'all"

sentence = word_1 + " " + word_2 + "!"
sentence

In [0]:
# Examples of repetition

# Repeat 1 ten times
repeated_ones = [1] * 10
print("This list contains '1' repeated 10 times:", repeated_ones)

# The list to repeat can contain multiple elements
repeated_words = ["Howdy", "y'all"] * 5
print(repeated_words)

In [0]:
# Repetition for strings

ten_hellos = "Hello!" * 10
ten_hellos

Other operators such as `-` and `/` do not work with Python lists.

In [0]:
# Example of `-` operator failing

sub_fail = [1, 2, 3] - [1, 1 ,1]

In [0]:
# Example of `/` operator failing

div_fail = [1, 2, 3] / [4, 4, 4]

##Exercise - Nested Lists
Add item 7000 after 6000 in the list containing 6000 

```
my_list = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
```
Expected Output:


```
my_list = [10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]
```

### Tuples

Tuples also represent a group of items / objects, but unlike lists, they are _immutable_. This means that they cannot be appended to, and the items inside them cannot be replaced with others, only accessed.

Are commonly used storing pairs of something (like coordinates or first name, last name pairs).

Items can be accessed using indexes similar to lists.

In [0]:
# A look at indexing in tuples 
items = (1, 2, 3, "Howdy!")

print("FIRST object in items:", items[0])

print("LAST object in items:", items[len(items)-1])

# We can use negative indexing in tuples too!
print("LAST object in items:", items[-1])

# Tuples also allow slicing!
print("Objects 1-3 in items:", items[:3])

In [0]:
# We can access values using indexing, but tuples are immutable, thus values cannot
# be set.

items = (1, 2, 5, 4)
# This will throw an error
items[2] = 3

In [0]:
# Appending fails as well
items = (1, 2, 5, 4)

# This will fail
items.append(5)

In [0]:
# Accessing out-of-bound indices on tuples will fail
items = (1, 2, 5, 4)
items[10]