
Given below are 15 entries. Each respective entry corresponds to student name, and the courses they are attending respectively.

```
coursesList = ['Math', 'English', 'History', 'Science', 'Geography','English', 'Science','Math',  'History', 'History', 'Geography','Math', 'English', 'Math', 'English']


namesList = ['rio', 'moscow', 'berlin', 'denver', 'oslo', 'helsinki', 'nairobi', 'palermo', 'lisbon', 'stockholm', 'rio', 'denver', 'lisbon' , 'helsinki', 'palermo']
```

As you can see, this is messy. A better way to handle this is to create a ***School Dictionary***: i.e. pack the above data in one dictionary with each entry in the following format of ***key,value*** pair:

`'Name' : [list_of_courses]`

e.g .
`'rio' : ['Math', 'Geography']`


# **QUESTION**

Given two lists, `coursesList` and `namesList`, ask the user for a course name `courseInput` and print classmates names i.e. names of all the students enrolled in the same course `courseInput`. 

Format of the output - a **sorted** list of student names separated by `" "` on a single line.

**Output list must be sorted alphabetically to make it easier for grading**

In [0]:


##########################################################################################################
# Important point ::::                                                                                  ##
                                                                                                        ##
# Converting any list to a set and then again to list                                                   ##
# will change the order of the elements in the list,                                                    ##
# as the intermediate set will be scrambled randomly                                                    ##
# therefore, to not create conflicts in the received answers and our answer, we ask for a sorted list.  ##
                                                                                                        ##
##########################################################################################################

coursesList = ['Math', 'English', 'History', 'Science', 'Geography','English', 'Science',
               'Math', 'History', 'History', 'Geography','Math', 'English', 'Math', 'English'] 
namesList = ['rio', 'moscow', 'berlin', 'denver', 'oslo', 'helsinki', 'nairobi', 
             'palermo', 'lisbon', 'stockholm', 'rio', 'denver', 'lisbon' , 'helsinki', 'palermo']

# Step 1: Ask user for course name for which they need to see enrolled students
courseInput = 




# Step 2: Populate school dictionary as explained earlier. Also, think how to iterate over two lists simultaneously.
school = {}





# Step 3: Find names of students enrolled in same course i.e. courseInput
classmates = []



# Step 4:  Print classmates in sorted order (alphabetically)

**Sample** 

Input: `English`

Output: `helsinki lisbon moscow palermo`